plugins {
    id 'com.android.application' version '8.5.2'
}

android {
    namespace 'ru.nova.assistant'
    compileSdk 34

    defaultConfig {
        applicationId 'ru.nova.assistant'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
